### ISSUE TITLE
Choosing the target project to deploy the sandbox

### ISSUE THREAD

**Issue by empiricaldevops** [GoogleCloudPlatform/cloud-ops-sandbox#1005]
The current instructions in the documentation doesn't tell how to create the sandbox in an already existing project.  Although it's possible to find that out using `sandboxctl create --help` command, adding it explicitly in the documentation will be helpful.

Ask: Add to the documentation that you can can specify the existing project of your choice to deploy the sandbox by using `sandboxctl create -p <project-id>`

**Comment by minherz** [comment]
Thank you for letting us know.
The installation script provides the list of projects that a user has owner permissions on them and propose to select one of them or create a new project. I assume your experience is different.
Can you please share the more detailed step-by-step instruction about what you do to install Sandbox? Do you use "Cloud Shell button" in README, clone the repo or you do something different?
I appreciate if you will be able to share an output that you see in the step when a project is expected to be selected/created (either a screenshot or the output copy/paste).

**Comment by minherz** [comment]
The 0.9 versions of `sandboxctl` are no longer create projects. The behavior is _always_ to create the Cloud Ops Sandbox instance in the existing project that is provided as a parameter to `sandboxctl create` command. The documentation in README and walkthrough explicitly instruct to provide the project ID as a parameter to the "create" command. If the command is invoked without the project parameter, CLI prints out error message.
Feel free to reopen this issue if the error message is not clear.
