### ISSUE TITLE
[Bug]: GitHub badges on the root README do not reflect any meaningful status

### ISSUE THREAD

**Issue by bourgeoisor** [GoogleCloudPlatform/cloud-ops-sandbox#1051]
### Version of Cloud Ops Sandbox

N/A

### Your client machine OS?

iOS

### Tell us, what is a problem?

Currently, the badges on the [root README](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/main/README.md) do not show any meaningful status. They show the latest status of these workflows:
- https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/actions/workflows/terraform.yaml
- https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/actions/workflows/cli.yaml

But since these workflows only runs on PRs (and not on main), the badges reflect the status of the last PR that happened to have ran those workflows (whether or not that PR has even been merged in).

### What you expected to happen?

We should:
- Make sure that the Terraform and CLI workflows run both on PRs _and_ on main
- Update the root README badges to only show "latest main" run of these workflows (not PRs)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by minherz** [comment]
Cloud Ops Sandbox adapt the [trunk-based] model. In this model each release is maintained in the dedicated branch and the main branch _may_ represent the current development status of the development on top of the latest X.Y.Z version.

The current goal for showing the status of the latest CLI and Terraform workflows was based on certain expectations for the development velocity that did not come true.

What is a goal of the request to "only show latest main run"? Limiting the aforementioned workflows to run only on PRs that submitted to the `main` branch prevents any development work that takes place in any other branch from being validated vs. these workflows.

[trunk-based]: https://trunkbaseddevelopment.com/

**Comment by minherz** [comment]
It is decided that we remove the badges from the README file at the root of the repo for now. The badges will be removed no later than 0.10.0 version release
