### ISSUE TITLE
[Bug]: sandboxctl doesn't handle the environment variable VERSION

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/cloud-ops-sandbox#1058]
### Version of Cloud Ops Sandbox

0.9.2

### Your client machine OS?

Linux

### Tell us, what is a problem?

On running `sandboxctl`, it fails with the following error message.

```
./provisioning/sandboxctl: line 214: VERSION: unbound variable
```

I looked up [the source code](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/main/provisioning/sandboxctl#L214), and found that the environment variable VERSION is just defined here and not initialized.

It should be `SANDBOX_VERSION` instead.

### What you expected to happen?

`sandboxctl` runs without any error message because of syntax error of the bash script.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by minherz** [comment]
Duplicates #1045
