### ISSUE TITLE
[Bug]: nit: document issue for local development

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/cloud-ops-sandbox#1059]
### Version of Cloud Ops Sandbox

0.9.2

### Your client machine OS?

Linux

### Tell us, what is a problem?

In [the document](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/tree/main/docs#customize-launch), the user can deploy the demo with the following commands.

```
git clone https://github.com/GoogleCloudPlatform/cloud-ops-sandbox
gcloud auth application-default loging
cloud-ops-sandbox/provisioning/sandboxctl -p PROJECT_ID
```

However, this section contains a couple of typos and obsolete commands.

1. `gcloud auth application-default loging` should be `gcloud auth application-default login`
2. `cloud-ops-sandbox/provisioning/sandboxctl -p PROJECT_ID` should be `cloud-ops-sandbox/provisioning/sandboxctl create -p PROJECT_ID`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by minherz** [comment]
Duplicates #1047
