### ISSUE TITLE
Running install.sh multiple times

### ISSUE THREAD

**Issue by Daniel-Sanche** [GoogleCloudPlatform/cloud-ops-sandbox#11]
How do we want the script to behave when it is run multiple times? Currently, terraform will skip deploying a new project, but the load balancer portion will create a new load balancer.

Do we want the script to cancel if it sees tfstate files in the current directory? Or should it always deploy another sandbox instance?  Or something else?

**Comment by simonz130** [comment]
Good point. We should make it idempotent:

For each step (such as creating a loadgen, deploying manfiests, etc) - we should make sure that the result of running the script once with that step or multiple times with that step yield the same end result. 
Compare desired state to deployed state and do the delta. Terraform already has that baked in.
We need to update the pieces of install.sh: it should not create additional load balancers but rather remove existing and create a new one instead, etc.

It can wait until after Next though.

**Comment by jiang95-dev** [comment]
@simonz130 This should be delayed since load generator will be moved to Cloud Run.
