### ISSUE TITLE
Remove readiness and liveness probes from recommendation service

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#15]
Recommendation service probes fail frequently. Removing them makes the service more stable.
We should do it in both main and Next'19 branches.

**Comment by DanSanche** [comment]
Hey @simonz130 , is this issue still active? If so, I'll take a look this week

**Comment by simonz130** [comment]
@Daniel-Sanche, could you please take a look? We are out of SLO with this one :)
