### ISSUE TITLE
Move monitoring terraform into main installation terraform

### ISSUE THREAD

**Issue by nicklin37** [GoogleCloudPlatform/cloud-ops-sandbox#255]
We want to have the monitoring terraform be setup with the main terraform in one go without having to call terraform init/apply again.

**Comment by nicklin37** [comment]
This task is currently blocked by Workspaces creation. Once we figure out what to do there we can use a Terraform module to integrate the monitoring Terraform into the main Terraform. It would be essentially identical to what we did in #449 for the loadgen module. Fixing this also closes #453

**Comment by Ayelet41** [comment]
After internal discussion, while there is place to improve the module there is no need to move it to be part of the installation especially as the monitors are for application and not infrastructure and need to be in a separate step, and at this time we do not want to refactor the services deployment.
