### ISSUE TITLE
Google Cloud Debugger not compatible with our python docker image

### ISSUE THREAD

**Issue by glozow** [GoogleCloudPlatform/cloud-ops-sandbox#325]
Our python services, recommendation and email, are written using python3 but also try to use the library [Google Cloud Debugger](https://pypi.org/project/google-python-cloud-debugger/) which only supports python 2.7. I'm guessing there is either another equivalent library or that support is being developed right now, but what's in our services isn't working right now. 

You can verify that `pip3 install google-cloud-debugger` errors: 

```
ERROR: Could not find a version that satisfies the requirement google-cloud-debugger (from versions: none)
ERROR: No matching distribution found for google-cloud-debugger
```

Because there isn't a package that works with our version 3 requirement. Similar things happen when running `pip-compile` in either email or recommendation if we have this package in requirements.in. I got around this while working on the service by removing the associated packages before running `pip-compile`, then putting then back in. The email service actually has all googleclouddebugger code commented out so it wasn't a problem for me, but then I wonder if we should just delete it.

When running, the recommendation service errors due to debugger:
```
   File "/usr/local/lib/python3.7/site-packages/googleclouddebugger/gcp_hub_client.py", line 346, in _RegisterDebuggee
     response = service.debuggees().register(body=request).execute()
   File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
     return wrapped(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
     raise HttpError(resp, content, uri=self.uri)
 googleapiclient.errors.HttpError: <HttpError 403 when requesting https://clouddebugger.googleapis.com/v2/controller/debuggees/register?alt=json returned "Request had insufficient authentication scopes.">
```

**Comment by simonz130** [comment]
Apparently, Python Debugger has only experimental support for Python 3: https://github.com/GoogleCloudPlatform/cloud-debug-python
At the same time, Python2 is deprecated runtime on GCP, so in order to not lose Python Debugging in Sandbox, we need to use experimental agent. 

Thanks for reporting - this is severe issue!

**Comment by simonz130** [comment]
Hey @jiang95-dev - even though it's not directly related to provisioning, I want you to take a look and try to fix this.

**Comment by daniel-sanche** [comment]
It looks like the `google-cloud-debugger` was deprecated. New updates are being pushed to `google-python-cloud-debugger`.

Recomendationservice seemed to already have this fix, but I opened a PR to bring emailservice up to date
