### ISSUE TITLE
There should be a command to retrieve all URLs for created Sandbox

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#34]
When Sandbox creation completes, the log shows a list of key URLs for next steps.
There should be a command to retrieve this URLs at any time after project creation.

**Comment by Ayelet41** [comment]
@simonz130 Is this sandboxctl describe or anything else need to be done?

**Comment by simonz130** [comment]
No, this is pretty much fixing this issue. I'll close it. Thank you!
