### ISSUE TITLE
Users can't set up Cloud Shell on Alpha

### ISSUE THREAD

**Issue by nicoleczhu** [GoogleCloudPlatform/cloud-ops-sandbox#363]
Related to #362 , Cloud Shell setup links are broken in both README and stackdriver-sandbox.dev. External users cannot use Sandbox at the moment.

Suggested: 
- Temporarily revert to the [old link](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/stackdriver-sandbox.git&cloudshell_git_branch=master&cloudshell_working_dir=terraform&cloudshell_image=gcr.io/cloudshell-images/cloudshell) that uses default image
- Do nothing, as this may be resolved soon

_Feel free to close this issue if it's redudant @eaberman , I'm mostly familiarizing myself with our workflows right now_ 😄

**Comment by eaberman** [comment]
Are you getting specific error messages?

**Comment by eaberman** [comment]
Update: I rebuild the image and labelled the latest rebuild with tag `v0.2.0`. After this, the image appeared to work. This may be indicative of a rebuild of the Base Cloud Shell image by the Cloud Shell team (which our custom image was not responsive to.) This illustrates the need to create a Build trigger which rebuilds the image any time the base image gets rebuilt.

**Comment by nicoleczhu** [comment]
Neat. @eaberman this is what I was seeing: 
<img width="804" alt="Screen Shot 2020-08-24 at 9 12 12 AM" src="https://user-images.githubusercontent.com/69952136/91071045-897dff80-e5ec-11ea-9522-d50a17cf4a8a.png">

`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`
`setupsession:1 Failed to load resource: the server responded with a status of 502 ()`

**Comment by eaberman** [comment]
Thanks for letting me know! I believe it should be resolved now. Let me know if that is not the case.

**Comment by nicoleczhu** [comment]
It is resolved. Nice :)
