### ISSUE TITLE
Order billing accounts in provisioning in case insensitive order

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#365]

**Comment by nicoleczhu** [comment]
Related suggestion: inform users that this provisioning process "will take a while" to manage expectations :) .

**Comment by simonz130** [comment]
@Crash-GHaun - could you please take a look -it's either obsolete(fixed) or should be easy to fix.

**Comment by Crash-GHaun** [comment]
Will do when I back in the office next week :)

**Comment by Ayelet41** [comment]
Please note I updated the message in Neo Tutorial- see linked PR.

**Comment by minherz** [comment]
Missing the content
