### ISSUE TITLE
Profiler agent fails when provisioning new Sandbox

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#371]
This is what I see in error reporting when provisioning new Sandbox (it doesn't say which node microservice that is)
![image](https://user-images.githubusercontent.com/32641282/91104731-2a87ad00-e623-11ea-9d07-7ea8c7410d9a.png)
(node:1) UnhandledPromiseRejectionWarning: Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by gzhao408** [comment]
The Profiler is not related to this release and currency/payment profiling have never worked before afaik. I do think this is an issue, but not part of this release (and thus not p1).

Profiler for currency in the last 30 days:
![image](https://user-images.githubusercontent.com/25183001/91110122-be607580-e631-11ea-8fe8-9e6875731cab.png)

Profiler for currency in the last 1 hour:
![image](https://user-images.githubusercontent.com/25183001/91110224-fc5d9980-e631-11ea-9e6d-e14ffdcd94a5.png)

Profiler for payment in the last 30 days:
![image](https://user-images.githubusercontent.com/25183001/91110067-a25cd400-e631-11ea-8904-0ee576931ef3.png)

Profiler for payment in the last 1 hour:
![image](https://user-images.githubusercontent.com/25183001/91110243-08495b80-e632-11ea-9d69-5eea0f035f25.png)

(which, I infer, means neither of them were affected by changes made in the last 30 days)

For contrast, Profiler for checkout in the last 30 days:
![image](https://user-images.githubusercontent.com/25183001/91110156-d1734580-e631-11ea-97f2-ac59ed05be1f.png)

And Profiler for checkout in the last 1 hour:
![image](https://user-images.githubusercontent.com/25183001/91110277-2f079200-e632-11ea-8121-64892223ff17.png)

**Comment by simonz130** [comment]
I think it's possible that what you see using non-google.com account differs from what I see using google.com account.
For me, service creation and exposing external IP fails, so the only thing I see for Profiling is the error mentioned in this bug. I can't send traffic to produce the flame charts you see because IP is not externally open for me.

Also, profiler depends on node runtime, which we updated in this release, so makes sense we didn't find it in previous release.

Let's try to fix this.

**Comment by gzhao408** [comment]
These screenshots are taken from my gz-sandbox project, which is a google account 🤔 the previous release happened within the last 30 days. I can also start up a sandbox built from the repo ~2 months ago and see if the profiler works there.

So the services don't come up at all? Does the tracing work?

We could try reverting the node runtime bump or trying out different versions > the one needed by the debugger. It could also just require passing in a `PROJECT_ID` environment variable. Sometimes it's empty, though, and the auth is done in a different way.

**Comment by gzhao408** [comment]
Just tested from current master on a @ gmail account, the Profiler shows up for payment like this:

![image](https://user-images.githubusercontent.com/25183001/91211138-20b58680-e6c3-11ea-8e72-1eb858945fcb.png)

![image](https://user-images.githubusercontent.com/25183001/91212840-9de1fb00-e6c5-11ea-9ac0-f91b0361ac83.png)

**Comment by gzhao408** [comment]
(current master on a gmail account)
![image](https://user-images.githubusercontent.com/25183001/91213273-31b3c700-e6c6-11ea-915b-7aad085f4b5d.png)


(v0.2.0 on a gmail account)
![image](https://user-images.githubusercontent.com/25183001/91213043-e4cff080-e6c5-11ea-8497-769afd19b1ba.png)

(current master using gz-sandbox, which is google account project created months ago)
![image](https://user-images.githubusercontent.com/25183001/91213241-26f93200-e6c6-11ea-972b-c01abe20845b.png)
