### ISSUE TITLE
Errors creating istio monitoring services during install

### ISSUE THREAD

**Issue by gzhao408** [GoogleCloudPlatform/cloud-ops-sandbox#374]
After I create the monitoring workspace and continue with the provisioning script:
![image](https://user-images.githubusercontent.com/25183001/91109669-873d9480-e630-11ea-94e8-6df9a9f764c5.png)

Afterward, I don't see the istio services (only the custom services):
![image](https://user-images.githubusercontent.com/25183001/91109728-ae946180-e630-11ea-98fb-d23a67da8a81.png)

**Comment by nicklin37** [comment]
Closed by #361
