### ISSUE TITLE
Loadgenerator shows incorrect IP address sometimes

### ISSUE THREAD

**Issue by nicklin37** [GoogleCloudPlatform/cloud-ops-sandbox#378]
When provisioning a Sandbox from an existing Sandbox, sometimes the loadgenerator will show two different IP addresses and one of them (the first one) will be incorrect. 
![Screenshot 2020-08-24 at 4 16 40 PM - Display 2](https://user-images.githubusercontent.com/33471452/91202257-64ee5a00-e6b6-11ea-9d03-02bf21873583.png)

**Comment by Daniel-Sanche** [comment]
Can you share the project this happened in?

**Comment by nicklin37** [comment]
https://console.cloud.google.com/home/dashboard?project=cloud-ops-sandbox-475973268 - just added you as an owner (it's a non-Google account). @jiang95-dev also mentioned he saw this error.
