### ISSUE TITLE
Add validation script to Cloudbuild for Custom Image Rebuilds

### ISSUE THREAD

**Issue by eaberman** [GoogleCloudPlatform/cloud-ops-sandbox#388]
In `cloudshell-image/cloudbuild.yaml`, there was previously a validation script run upon each image built and pushed to the Cloud Source Repo. In the future, it would be ideal to include that script once again.

**Comment by Daniel-Sanche** [comment]
> Additionally, in the update-custom-image.yaml file, it would be ideal to stream the builds using cloud build logging. This was not included in this release due to permissions issues.

I think that should be it's own issue too

**Comment by eaberman** [comment]
Okay, I will add that as its own issue too!
