### ISSUE TITLE
Create new sandbox intro video for the landing page

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#40]
https://www.youtube.com/watch?v=QW7bnzqSawk&t=24

**Comment by Ayelet41** [comment]
@simonz130 As this video is outdated, is this request still needed?

**Comment by simonz130** [comment]
We need to create a new video and then embed it in the landing page.
There was internal discussion about this and it was postponed to at least q3.

**Comment by minherz** [comment]
Closing the issue due to low demand and expected redesign of the project.
