### ISSUE TITLE
Re-using existing Sandbox fails for Google/Non-Googler

### ISSUE THREAD

**Issue by nicklin37** [GoogleCloudPlatform/cloud-ops-sandbox#444]
There seems to be an issue with the "authenticateCluster" step in the install script, multiple zones are retrieved for the cluster.

![Screenshot 2020-09-09 at 10 28 56 AM - Display 2](https://user-images.githubusercontent.com/33471452/92633254-5d6aab80-f287-11ea-932a-f61d0edd9b9d.png)

Running this command `gcloud container clusters list --filter="name:cloud-ops-sandbox" --project $project_id --format="value(zone)"` also produces two zones

**Comment by nicklin37** [comment]
Can be fixed if we did this but it shows a warning? 
```
gcloud container clusters list --filter="name = cloud-ops-sandbox" --project cloud-ops-sandbox-1014763488 --format="value(zone)"
us-central1-b
WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  name=cloud-ops-sandbox currently does not match but will match in the near future.  Run `gcloud topic filters` for details.
```

**Comment by nicklin37** [comment]
https://cloud.google.com/sdk/gcloud/reference/topic/filters

Using the colon is matching extensions of the "cloud-ops-sandbox" atm

**Comment by nicklin37** [comment]
> Can be fixed if we did this but it shows a warning?
> 
> ```
> gcloud container clusters list --filter="name = cloud-ops-sandbox" --project cloud-ops-sandbox-1014763488 --format="value(zone)"
> us-central1-b
> WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  name=cloud-ops-sandbox currently does not match but will match in the near future.  Run `gcloud topic filters` for details.
> ```

Note that here the sandbox cluster is in us-central1-b and the loadgen cluster is in us-west1-b.

**Comment by simonz130** [comment]
Should we just rename loadgen cluster to something that doesn't have the same prefix with the main cluster?

**Comment by Daniel-Sanche** [comment]
Sorry, I just saw this issue. Yeah, I think it's best to rename the loadgen cluster, I have a branch set up now, will open a PR soon
