### ISSUE TITLE
Difference in code resulting in Invalid Snapshot Position Error

### ISSUE THREAD

**Issue by eaberman** [GoogleCloudPlatform/cloud-ops-sandbox#47]
**Description:** A  user may get an "Invalid Snapshot Position" Error when following [these steps to create a snapshot](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/blob/master/docs/README.md#create-a-snapshot) in the Stackdriver Sandbox User Guide. This made it impossible to see any values coming from the application, since the snapshot was never activated.

**Error:** The error text reads: "Invalid snapshot position: Loaded script contained _x_ lines. Please ensure that the snapshot was set in the same code version as the deployed source." A picture is shown below.
![Screenshot 2020-07-01 at 12 14 41 PM](https://user-images.githubusercontent.com/38052620/86644308-04d71380-bfa3-11ea-944d-ec8ee4984a76.png)

**Fix:** This error is occurring because the service is deployed using container images that were created from the source code that is earlier than the currently checked-in version on GitHub. One possible fix is that the service should be deployed using updated container images from the most recent version.

**Comment by jiang95-dev** [comment]
@eaberman Should we just change the source repo in the README to be same as the container image?

**Comment by eaberman** [comment]
Updating the documentation would definitely help! Since it specifically says to click on line 121, if you know the line which is more updated and reflects the current container image, I believe that would make it more clear to the user!

**Comment by simonz130** [comment]
Closing it as it was fixed in #481
