### ISSUE TITLE
Make cloudshell walkthrough tutorial shorter

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#500]

**Comment by Ayelet41** [comment]
@simonz130 Can you clarify do you want to reduce the text and reference full doc or remove sections?

**Comment by simonz130** [comment]
Remove sections. 

We now have two tutorials:
1) Cloud Shell walkthrough (Neos) that opens to the right of the screen when clicking "open in cloud shell" button
2) Comprehensive walkthrough tutorial: https://cloud-ops-sandbox.dev/docs/

Currently (1) and (2) are similar content but in (2) this content is presented more comprehensively and with images. 

We should keep (2) as comprehensive version and reduce (1) to project overview - simple, short and concise text. It should explain what happens when new Sandbox is provisioned, also talk about what are next steps (e.g. SRE recipes, comprehensive tutorial link, how to send loadgen). Currently (1) is 17 pages. It should be 6-7 max.
