### ISSUE TITLE
Walkthrough tutorials should mention creation of workspaces manually

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#501]

**Comment by Ayelet41** [comment]
@simonz130 To add in set up screen or prerequet, what do you think make more sense?

**Comment by Ayelet41** [comment]
⚠️ Please create a monitoring workspace for the project by clicking on the following link:
  https://console.cloud.google.com/monitoring?project=cloud-ops-sandbox-<>

When you are done, please PRESS ENTER TO CONTINUE

**Comment by simonz130** [comment]
Agree, we need to mention workspace creation with some form of warning the user. The goal is eventually to automate this if default workspace feature becomes reality or if workspace API is public.

**Comment by Ayelet41** [comment]
Already mention manual creating. Waiting for API integration.
