### ISSUE TITLE
Majorly update services written in Go

### ISSUE THREAD

**Issue by nicoleczhu** [GoogleCloudPlatform/cloud-ops-sandbox#507]
Renovate bot hasn't been updating Go packages. And it seems a lot of our errors in logs stem from outdated Go dependencies: 

0. Version control gopkg.lock/toml is deprecated. We should update to use Go.mod/sum. This might be why renovatebot isn't catching updates for go?

1. A lot of errors happen in go containers during provisioning, example: 
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
Error
2020-10-06 13:37:20.659 PDT
A future release of golang/protobuf will delete this package,
Error
2020-10-06 13:37:20.659 PDT
which has long been excluded from the compatibility promise.
```

**Comment by ymotongpoo** [comment]
protoc now we are using is rather old. the upgrade was part of #676 but reverted to avoid large breaking changes in a single PR.

I can take this after #714, #715, #716 are merged.

**Comment by ymotongpoo** [comment]
And #724 is also merged. Main issues mentioned in this issue seems fixed and closing this accordingly.
