### ISSUE TITLE
Sandbox doesn't start provisioning after choosing a billing account

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#524]
When a user tired to create a new Sandbox, they had to choose billing account:
![image (1)](https://user-images.githubusercontent.com/32641282/96025438-fd2cd380-0e09-11eb-9d77-b31d91686f9a.png)

After choosing option 1, they got an error:
![image (2)](https://user-images.githubusercontent.com/32641282/96025501-0fa70d00-0e0a-11eb-8828-492bc83b0edf.png)

Seems like we show service accounts that are disabled in the choice list. Pending confirmation from the user.

**Comment by simonz130** [comment]
Update: billing account was active.

Further investigation shows that this is a known issue:
https://github.com/hashicorp/terraform-provider-google/issues/3429

Based on the bug above, adding sleep or retries might solve it:
https://github.com/EngineerBetter/concourse-gcp-tf-bootstrap/blob/master/tf/pipeline-reqs.tf#L30-L32

**Comment by treedy** [comment]
I ran into this issue, too. As a work around I disabled billing for the project, then reattached the billing account and it proceeded.

**Comment by ymotongpoo** [comment]
Looking at this. @simonz130 @treedy is this happen every time? I tried to reproduce this and could not. My demo account is set with Billing Account and the account is automatically set during the provisioning.

**Comment by treedy** [comment]
This was intermittent before I made changes the changes in PR #570 . After that PR, I didn't see it once, but I haven't tried enough times to say that this doesn't happen at all.

**Comment by keenan-devrel** [comment]
Closing. Will re-open if it resurfaces.
