### ISSUE TITLE
docs: how to manufacture errors for Error Reporting

### ISSUE THREAD

**Issue by glozow** [GoogleCloudPlatform/cloud-ops-sandbox#53]
The [Error Reporting](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/blob/master/docs/README.md#stackdriver-error-reporting) section would be a more powerful demonstration if the user were able to manufacture some errors and see them reported on the UI. The docs could have some "how to break it" instructions, e.g. stopping nodes through the GCP console or a particular pattern using the load generator.

**Comment by simonz130** [comment]
This will be done by 20%er later on

**Comment by Ayelet41** [comment]
@simonz130 Can you clarify, is the motivation to use SRE recipes or different suggested flow?
