### ISSUE TITLE
Run Provisioning Test fails in e2e-latest (sporadic)

### ISSUE THREAD

**Issue by nicoleczhu** [GoogleCloudPlatform/cloud-ops-sandbox#530]
E2e Tests are often (but not always) failing on `Run Provisioning Test` step: 
`Test if the load generation works properly when started [with pattern=None] ... FAIL`

As an example, here are two runs on the same (unrelated) code, ~4 hours apart:
[passing] https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/runs/1277128330?check_suite_focus=true
[failing] https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/runs/1278054467?check_suite_focus=true
```

Test if the load generation works properly when started [with pattern=None] ... FAIL

======================================================================
FAIL: testStartSwarm_0 (loadgen_test.TestLoadGenerator)
Test if the load generation works properly when started [with pattern=None]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/code/loadgen_test.py", line 108, in testStartSwarm
    self.assertTrue(stats['total_rps'] > 0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5 tests in 30.067s

FAILED (failures=1)
Error: Process completed with exit code 1.
```

@Daniel-Sanche fyi. Lemme know if it's anything I can help fix

**Comment by daniel-sanche** [comment]
I don't think we've run into this problem recently, and I see a lot of changes on the e2e scripts since October. I'm going to close this for now, but will re-open if it seems to still be a problem
