### ISSUE TITLE
Explain how to use loadgen in user guide

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#540]

**Comment by treedy** [comment]
@simonz130 Is there documentation of certain scenarios and matching traffic shapes? Or what is the desired pieces of documentation for this particular issue?

**Comment by Ayelet41** [comment]
@simonz130 Do we want to add it as part of tutorial or documentation ?
As I see, when starting with Sandbox you use the tutorial and for that regards UI reference is sufficient. 
And for 'advance' you refer to documentation. 

I made some changes for the current UI tutorial for clarity and link to external doc.
https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/652

**Comment by simonz130** [comment]
For loadgen, we should briefly mention it in Cloud Shell tutorial (Neos) and expand with details in docs.
The goal of Neos tutorial is to provide a quick walkthrough helping customers discover what's available in Sandbox. It's not meant to be a comprehensive doc and we don't want users to spend too much time on it.
