### ISSUE TITLE
Warn user that launching sandbox will terminate current Cloud Shell sessions

### ISSUE THREAD

**Issue by treedy** [GoogleCloudPlatform/cloud-ops-sandbox#550]
When a user clicks on the launch button on the website or in the documentation, it launches a new Cloud Shell with a custom image. This will cause any running Cloud Shell sessions to be terminated for the user. The website and all documentation should warn the user to save any changes and gracefully terminate any processes running in Cloud Shell.

**Comment by simonz130** [comment]
We can start with the warning but really we want to embed the build of Sandbox in the custom cloud shell image we use. If that happens, we might change "open in cloud shell" to not always use fresh image of cloud shell.
