### ISSUE TITLE
sandboxctl create fails with "Use of this bucket name is restricted"

### ISSUE THREAD

**Issue by treedy** [GoogleCloudPlatform/cloud-ops-sandbox#576]
Master branch `sandboxctl create` errors out with `Error: googleapi: Error 400: Use of this bucket name is restricted: '<project_id>-ratingservice-deployables-<random-12hexchars>', invalid`.

The "it" GCS bucket resource's name is too long. The is the issue in `terraform/ratingservice/main.tf`. The suffix's byte length is 6 which is 12 hex characters. The max suffix length I could use when creating the bucket is 8 characters or 4 bytes.

https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/cfdb1b76501bdf6b1c60f7a406ec0b860662f8cb/terraform/ratingservice/main.tf#L44-L46

and

https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/cfdb1b76501bdf6b1c60f7a406ec0b860662f8cb/terraform/ratingservice/main.tf#L93-L96

**Comment by treedy** [comment]
@minherz Saw you were the last to work on `ratingservice/main.tf`. Bucket name lengths can only be 63 characters long. Currently, the project names are 28 characters (eg, `cloud-ops-sandbox-1503263247`). Then adding the 27 characters from `-ratingservice-deployables-` gives you 55 total characters. Adding 12 randomized hex characters yields a total of 67.

Do you forsee any problem with using only 8 random hex chars for the suffix?

**Comment by minherz** [comment]
@treedy thank you for noticing. I will reduce the length of the name in the next PR. The concern was that bucket name cannot be reused for a long period of time but since it mainly runs on the same project, it should be OK to reduce the length to 2 hex digits (4 characters).
