### ISSUE TITLE
Automate checks against cloud shell

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#585]
We sometimes run into issues where the Cloud Shell environment can't be provisioned (https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/583). It would be useful to have checks in place so we can catch these early, instead of waiting for someone to report it manually

**Comment by Daniel-Sanche** [comment]
There seems to be a [Cloud Shell gRPC API](https://cloud.google.com/shell/docs/reference/rpc/google.cloud.shell.v1alpha1#google.cloud.shell.v1alpha1.CloudShellService.StartEnvironment) available that could be useful for this. But it doesn't seem like any client libraries are available, and the HTTP version doesn't have the endpoints required

**Comment by minherz** [comment]
Sandbox does not use a custom Cloud Shell.
