### ISSUE TITLE
Tutorial walkthrough is out of sync with current Sandbox

### ISSUE THREAD

**Issue by nicoleczhu** [GoogleCloudPlatform/cloud-ops-sandbox#600]
**Errors:**
- Step 9: Trace analysis report not autocreated
- Step 11: `gcloud debug source upload` yields ERROR: (gcloud.debug.source) Invalid choice: 'upload'.

**Nits**: 
- Step 1: Update tutorial to have users set up workspace monitoring first
- Step 1: Say something like, "this installation step may take up to 20 minutes (not a few minutes as it currently states). Go to the next step when installation is complete."

**Comment by Ayelet41** [comment]
@nicoleczhu Are the errors still relevant?
1) If so can you clarify what do you mean?
```Step 9: Trace analysis report not autocreated```

2) ```Step 11: gcloud debug source upload yields ERROR: (gcloud.debug.source) Invalid choice: 'upload'.```
Content moved to cloud_debugger.md under user guide and seems ok, could you have a look?
```gcloud beta debug source upload --project=cloud-ops-sandbox-68291054 --branch=6412930C2492B84D99F3 .```

**Comment by nicoleczhu** [comment]
@Ayelet41 thanks for flagging - this issue is outdated. Closing!
