### ISSUE TITLE
Add 1 min delay after workspace provisioning

### ISSUE THREAD

**Issue by Daniel-Sanche** [GoogleCloudPlatform/cloud-ops-sandbox#602]
It seems like there are some background operations that must complete after the workspace is enabled. We suggested adding a 1 minute delay to make sure the script avoids errors

**Comment by treedy** [comment]
@Daniel-Sanche is this still the case on master? I re-ordered the operations in terraform/install.sh so that the workspace creation is done immediately after the project is created. See PR #570

**Comment by Daniel-Sanche** [comment]
Yes, we encountered this issue as part of our pre-release tests this morning. We saw errors related to the alert policy:
![image](https://user-images.githubusercontent.com/3914119/102254483-7fdf1700-3ebd-11eb-8bf3-0c3c1e3b3e13.png)

**Comment by Daniel-Sanche** [comment]
I believe [this line](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/b8c1a690c917aaf5cf0d05ff1b6231e8fcd263ba/terraform/install.sh#L253) was added to avoid doing a generic 1 minute wait. I wonder why it didn't seem to help this time

**Comment by simonz130** [comment]
I created a few sandboxes as a Googler and so far none of them seemed to reproduce it. I will try 2 more but if it doesn't reproduce, I'll close it - maybe there was a glitch in service monitoring APis in the morning?

**Comment by simonz130** [comment]
I confirmed that there are no errors if you happen to create the workspace - basically @treedy works to mitigate the issue - we just can't force people to read messages and follow :) As soon as we get the automation in place for workspace creation - I believe this problem will go away.
