### ISSUE TITLE
Rating service doesn't show ratings when first deployed

### ISSUE THREAD

**Issue by Daniel-Sanche** [GoogleCloudPlatform/cloud-ops-sandbox#604]
After deployment finishes, it takes a few minutes for the rating service to start working

**Comment by minherz** [comment]
I've run several deployments and could not reproduce the problem. I will be looking to add a warm up API to the rating service if I find it can improve starting time.
If you experience this problem again, please let me know and do not delete the sandbox and/or its project.

**Comment by Daniel-Sanche** [comment]
Yeah, I haven't been seeing this in the latest update either. I'll close this for now, but if anyone sees it again, we can re-open and re-discuss
