### ISSUE TITLE
Frontend fails for active sandboxes for 2+ weeks

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#621]
I had a few Sandboxes created more than 2 weeks ago. When going to the frontend, this is the error I get on them:

rpc error: code = Unavailable desc = no healthy upstream
could not retrieve cart
main.(*frontendServer).homeHandler
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/handlers.go:64
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/github.com/gorilla/mux/mux.go:162
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opentelemetry.io/otel/instrumentation/othttp.(*Handler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opentelemetry.io/otel/instrumentation/othttp/handler.go:155
main.(*logHandler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/middleware.go:94
main.ensureSessionID.func1
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/middleware.go:116
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opencensus.io/plugin/ochttp/server.go:82
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1925
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by Daniel-Sanche** [comment]
I don't have any old sandboxes to test with, but I'll set up a new one and I can check back in a couple weeks

**Comment by Daniel-Sanche** [comment]
So far I haven't been able to reproduce this
