### ISSUE TITLE
Page link refers to 404

### ISSUE THREAD

**Issue by codeanit** [GoogleCloudPlatform/cloud-ops-sandbox#629]
# 404 Page

The link : [Code Labs](https://codelabs.developers.google.com/gcp-next/?cat=Monitoring) opens a 404 page.

Link location : https://github.com/GoogleCloudPlatform/cloud-ops-sandbox#next-steps.

**Comment by Daniel-Sanche** [comment]
Good catch, thanks! Opened a PR to address this: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/634

**Comment by Ayelet41** [comment]
@Daniel-Sanche This seems to be fixed, can it be closed or there is any pending item?

**Comment by Daniel-Sanche** [comment]
yes, sorry! this has been fixed
