### ISSUE TITLE
Trace ID and Span ID embedded logs in adservice are zero values, and trace data links don't work

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/cloud-ops-sandbox#655]
In the log entries from adservice, though the trace context information is embedded there, the value of them are all zero values. This causes the trouble when the user try to confirm the [trace details](https://cloud.google.com/logging/docs/view/logs-viewer-interface#trace_data) by clicking the icons because such traces don't exist.

![Screenshot from 2021-03-25 17-22-20](https://user-images.githubusercontent.com/145104/112441894-afd86900-8d8e-11eb-9960-823744cfdc64.png)

For better demo, I want this to be fixed.

**Comment by keenan-devrel** [comment]
Moved from bug to feature request to be done after structured logging.

**Comment by minherz** [comment]
Obsolete since locally maintained demo app is retired.
