### ISSUE TITLE
No matching distribution found for opentelemetry-ext-grpc==0.11b1

### ISSUE THREAD

**Issue by nicoleczhu** [GoogleCloudPlatform/cloud-ops-sandbox#658]
CI now fails on: `No matching distribution found for opentelemetry-ext-grpc==0.11b1`

I looked for the package here, but got a [404](https://pypi.org/project/opentelemetry-ext-grpc/) which leads me to suspect it was renamed or something. 

See the following merged PR (for an unrelated service) which fails in a Python service: 
https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/runs/2220786271

**Comment by daniel-sanche** [comment]
It looks like the `opentelemetry-ext-grpc` package has been de-listed. We can move to `opentelemetry-instrumentation-grpc`, as they recommend, but that will require some other package updates
