### ISSUE TITLE
Github actions runs into dependency issues with Hugo. We should work toward containerizing

### ISSUE THREAD

**Issue by Crash-GHaun** [GoogleCloudPlatform/cloud-ops-sandbox#662]
As per the PR: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/641

We are deploying the website using static files created via Hugo, but we should move toward containerization to build the site and deploy. This is a place holder issue for now.

**Comment by minherz** [comment]
We do not do any changes to the website. No need for this work now.
