### ISSUE TITLE
Review costs associated with Sandbox and optimize for reduced costs

### ISSUE THREAD

**Issue by Crash-GHaun** [GoogleCloudPlatform/cloud-ops-sandbox#664]
With the size of the Sandbox continuing to grow, we periodically need to review costs associated with deploying this sandbox. 

Ideally this Sandbox should stay within the $300 credit GCP offers. Creating this issue and assigning to myself for further review.

**Comment by simonz130** [comment]
Already taken care of @Ayelet41
