### ISSUE TITLE
Error: googleapi: Error 400: Project "cloud-ops-sandbox-20270XXXX" has no network named "default"., badRequest

### ISSUE THREAD

**Issue by karlitoz007** [GoogleCloudPlatform/cloud-ops-sandbox#678]
I have tried to create the Cloud Ops Sandbox in my GCP demo organization (`<LDAP>.altostrat.com`) using the "Get started now" button on https://cloud-ops-sandbox.dev/

However, the process is interrupted after few minutes with the following error during the Terraform execution:
```
Error: googleapi: Error 400: Project "cloud-ops-sandbox-202705302" has no network named "default"., badRequest

  on 03_gke_cluster.tf line 43, in resource "google_container_cluster" "gke":
  43: resource "google_container_cluster" "gke" {
```

I can share more details here or internally in case it could be useful to better identify the error.

**Comment by nicoleczhu** [comment]
Hi @karlitoz007 do you have your project's default network disabled, or is it disabled at your organizational level? If its disabled at the org level, you might run into other issues during deployment. One way around it is to create a temporary new GCP account and use the free credits. 

You can read about [default networks here](https://cloud.google.com/vpc/docs/vpc#default-network)

**Comment by karlitoz007** [comment]
Thanks @nicoleczhu for the quick answer. You are right, I have some organizational policies inherited, including the `constraints/compute.skipDefaultNetworkCreation`. So based on that, looks like I will need a different org/project where to run the demo. Have a great week!
