### ISSUE TITLE
OpenTelemetry python 1.0 for traces and new package names

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/cloud-ops-sandbox#718]
Just wanted to give an OpenTelemetry python update. The API and SDK have made 1.0 release and I've released stable versions of the GCP trace exporter and propagator. I had to split up the exporter packages because metrics are not stable and had to be removed for the time being. I've updated the PyPI pages to reflect the new packages (sorry about the names changing, shouldn't happen again!). The new packages going forward are:

- [opentelemetry-exporter-gcp-trace](https://pypi.org/project/opentelemetry-exporter-gcp-trace/) – stable
- [opentelemetry-propagator-gcp](https://pypi.org/project/opentelemetry-propagator-gcp/) – stable
- [opentelemetry-resourcedetector-gcp](https://pypi.org/project/opentelemetry-resourcedetector-gcp/) – not stable, we anticipate more changes and it's only needed for metrics
- [opentelemetry-exporter-gcp-monitoring](https://pypi.org/project/opentelemetry-exporter-gcp-monitoring/) – not stable, OTel metrics is undergoing lots of changes

Let me know if you have any questions or issues upgrading to these new versions!

**Comment by daniel-sanche** [comment]
It looks like Yoshi addressed this in https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/723/files

Although `opentelemetry-instrumentation` and `opentelemetry-instrumentation-grpc` are still `v0.19b0`. We'll have to keep an eye on those to make sure we upgrade when they're stable
