### ISSUE TITLE
Move sandboxctl into cloud shell base image

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#754]
We should consider adding sandboxctl to the official cloud shell image. This would allow users to continue communicating with their sandbox project if they lose connection to their custom cloud shell. This would also potentially allow us to completely remove the custom cloud shell image, and simplify our version deployment

**Comment by daniel-sanche** [comment]
For v.0.7.0, we should at least research how this would work

**Comment by daniel-sanche** [comment]
# Cloud Shell Base Image Research

## Benefits
- we can stop supporting the custom cloudshell image. 
  - this has been the main cause of bugs, since we have to rebuild the image weekly for it to keep working
- simplifies release artifacts
  - currently, we have three artifacts we need to release together: a cloudshell image, microservice images, and repo code
  - If we bake sandboxctl into the base cloudshell image, we can keep all release art5ifacts in a single bundle

## Problems to address

- we use the base image to launch sandboxctl automatically with the open in cloudshell button. I don't think we can do that if we move to the base image
  - possible solution: use [`cloudshell_print`](https://cloud.google.com/shell/docs/open-in-cloud-shell#url_parameters) to tell users how to use sandboxctl. One extra step
- testing could be difficult. 
  - We'd have to build a new test cloudshell image with the HEAD sandboxctl version. That makes it less representative of the real environment

## Dependencies

For sandboxctl to work in the cloud shell base image, we'll need also add support for our dependencies (taken from [dockerfile](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/cc96a0d53ed405e9d0617bc7662a600643ec1aac/cloud-shell/Dockerfile#L26)):
- python
  - click
  - google-cloud-pubsub
  - google-cloud-monitoring
- shell
  - terraform (can we use the built-in? Or do we need custom?)
  - postgresql-client 
  - jq

## Open Questions
- what would our new release process look like?
- What if we need to add more dependencies in the future? Is there a process for that?

**Comment by arbrown** [comment]
We have de-prioritized using the custom image moving forward.
