### ISSUE TITLE
Updates To 'Learn Cloud Operations' Website section

### ISSUE THREAD

**Issue by Ayelet41** [GoogleCloudPlatform/cloud-ops-sandbox#770]
1. OpenCensus instead of OpenTelemetry
2. Pre-built GKE  dashboard path is incorrect (might be Monitoring > Dashboards > GCP > GKE / Infrastructure Summary)
3. “Creating a logs-based metric” seems to be based on an old UI / workflow

**Comment by simonz130** [comment]
Do you mean the text below in (1)?

Note: The recommended solution for application instrumentation is **OpenCensus**, an open-source project that supports trace instrumentation in a variety of languages and that can export this data to Cloud.
