### ISSUE TITLE
Refactor user guide(hugo) to remove duplicates

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#772]
Currently there is a lot of mess between /docs and /website folders in the repo. There is a lot of duplication.

- [x] Remove duplication html for landing page
- [x] Optimize markdown files to sections
- [x] Break down [README.md](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/master/docs/README.md) to sections of hugo website [here](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/tree/master/website)

**Comment by minherz** [comment]
Website pages were reviewed. No need for further work now.
