### ISSUE TITLE
Create E2E test using last known released sandbox using sandboxctl from the main branch

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#775]
Create E2E test case for getting to use last known released sandbox version using sandboxctl from the main branch:

- Deploying a Sandbox (currently released version)
- Using bits from the main branch to re-use existing Sandbox (based on the latest released version). This would prevent incompatibility upgrades with Terraform.

**Comment by daniel-sanche** [comment]
This was added as[ "End to End - Upgrade"](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/actions/workflows/e2e-upgrade.yml)
