### ISSUE TITLE
Document a way to deploy website for testing

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#777]
Currently it's not clear how to deploy a pre-released copy of the website with user guide for testing purposes. We only have a link to "Open in Cloud Shell" button to test the changes.

We should have a way to test the changes to the website. Perhaps, we should deploy it as part of the CI and have a way to create a "private" CI run for testing purposes.

**Comment by daniel-sanche** [comment]
We have a ["Stage Website" GitHub Action](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/actions/workflows/manual-website.yml) to accomplish this. We should make sure it's well documented

**Comment by minherz** [comment]
We do not do any changes to the website. No need for this work now.
