### ISSUE TITLE
Reduce # of pages in NEOS tutorial

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#779]
Currently (as of 0.7.0) NEOS tutorial that is opening up next to Cloud Shell window has 9 pages. 6 of them look similar but shorter versions of what's available in the user guide.
We want to shorten the NEOS tutorial and move details into the user guide. (Hugo static website under /website folder)

**Comment by simonz130** [comment]
This is good ticket to take for folks who are getting started with Sandbox as contributors.

**Comment by simonz130** [comment]
@daniel-sanche could you please re-assign to one of the new contributors?

**Comment by napster-satyam** [comment]
Is the Issue still open @simonz130 ?

**Comment by minherz** [comment]
Reading through [NEOS tutorial](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/62b12c8f74d7e9d6b242fe1a3d18f7f343fcb00f/docs/tutorial.md) it looks like the content requires a rewrite.
The text is poorly fit to the width of the NEOS tutorial window and the use of the formatting options is bad. For example, the code option that shows the output of the automated deployment is displayed in the tutorial as a command ready for execution in Cloud Shell.
A lot of content should be replaced with a single link to the [User Guide](https://cloud-ops-sandbox.dev/docs/) (on [cloud-ops-sandbox.dev](https://cloud-ops-sandbox.dev/)).

I replace this issue with a new one that will request to revise all documentation and tutorials toward the upcoming changes.
