### ISSUE TITLE
Error 404: Could not find Application "cloud-ops-sandbox-XXXX" when using one-click installation

### ISSUE THREAD

**Issue by antigenius0910** [GoogleCloudPlatform/cloud-ops-sandbox#782]
Thanks for the awesome project!

I hit a bug when using the automated one-click installation for a new Sandbox cluster
First time, sandbox has been built and everything looks awesome. 
While the first sandbox still exists I accidentally build another sandbox and terminate it in the middle of the installation. 

I then delete both projects since the second Kub config file overwrite the first sandbox.

then whenever I try to build another sandbox it always end up with

```
Error: Error creating StandardAppVersion: googleapi: Error 404: Could not find Application "cloud-ops-sandbox-3920429050".
``` 

or 

```
Error: Error creating StandardAppVersion: googleapi: Error 404: Could not find Application "cloud-ops-sandbox-2431544720".

  on ratingservice/main.tf line 131, in resource "google_app_engine_standard_app_version" "default":
 131: resource "google_app_engine_standard_app_version" "default" {
```

this is the line which error out based on cloud shell output
https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/master/terraform/ratingservice/main.tf#L131

Seems like RatingService is running on App Engine so I don't understand which "Application" it is referring to. wonder if anyone have seen this issue before

![Screen Shot 2021-06-30 at 3 27 27 PM](https://user-images.githubusercontent.com/5915590/123919615-af67f380-d9b7-11eb-8294-4a2d7fb86fde.png)

Still have the last one incomplete sandbox alive for troubleshooting purpose.

**Comment by minherz** [comment]
@Ayelet41 can you have a look if it is a bug?

**Comment by Ayelet41** [comment]
@antigenius0910 If I understand correctly the scenario: 
you created sandbox(not completed) -->  created a _new_ sandbox (new project)--> deleted both -->(how?) --> Now you don't have any existing projects, but when you try to create new one you get the error, is that correct? 

Could you please clarify the flow and the below information, as this is very common flow, and I wasn't able to reproduce this issue:
 
1.  Do you see any sandbox projects when you running Sandbox Provisiong from `cloud-ops-sandbox.dev/`
```Checking for billing accounts...
Checking for project list...
Enter the number next to the project you would like to use:
1) create a new Sandbox
2) cloud-ops-sandbox-727029174 | [Jul-26-2021]
3) cancel ```

2. How did you deleted the old ones? were you able to use `sandboxctl destroy`?
3. By `then whenever I try to build another sandbox` you mean that in the installation you choose ` create a new Sandbox`? or launch a new Sandbox provisioning( cloud shell) on existing project(like 2 in the above example)? 
4. Assuming it the former, have you tried rerunning Terraform apply in the same project(choosing the existing project or running terraform/install.sh)?

**Comment by daniel-sanche** [comment]
I'm going to close this due to inactivity, and us not encountering the issue in recent versions. Feel free to re-open if you want us to keep investigating though
