### ISSUE TITLE
Hipster shop frontend OOMKilled on Cloud Ops Sandbox v0.7.0

### ISSUE THREAD

**Issue by t2tse** [GoogleCloudPlatform/cloud-ops-sandbox#791]
The default setup created by `sandboxctl` with locust running at 100 users, spawn rate of 2 would caused the `frontend` `server` container OOMKilled in a crash loop. I followed the guide and didn't expect that out of the box.
![image](https://user-images.githubusercontent.com/78811349/125380826-6e171100-e3c5-11eb-8a4b-c849c7cd830c.png)

Attached the chart below for what I have been seeing from Locust. 
![image](https://user-images.githubusercontent.com/78811349/125380793-5b044100-e3c5-11eb-8edb-a5734342f35b.png)

To workaround the issue, I changed the replica number from 1 to 2 for the trouble container and things stabilized. (Or I could increase the container memory limit)

@simonz130 thinks it is a bug. So I'm logging it here.

**Comment by simonz130** [comment]
@Ayelet41 could you please take a look at this?
