### ISSUE TITLE
Ability to specify zone or region GKE cluster should be deployed to

### ISSUE THREAD

**Issue by vishal84** [GoogleCloudPlatform/cloud-ops-sandbox#833]
RFE requesting the ability to specify the zone or region location for GKE clusters for the sandboxctl tool using parameters as input to specify location.  Zones/regions MUST be zones and regions defined by GCP documentation or will fail to deploy correctly.

**Comment by minherz** [comment]
This is possible by defining `gke_location` TF variable. Please, have a look into PR #811 .
