### ISSUE TITLE
Run Terraform fmt and Terraform validate as part CICD 

### ISSUE THREAD

**Issue by Ayelet41** [GoogleCloudPlatform/cloud-ops-sandbox#835]
1) Run `terraform fmt` and if value is return(e.g. file name) need to return to submitter that formating is needed i.e. `terraform fmt` is needed, if error is returned it need to be returned as is and addressed by submitter. 
2) Run `terraform validate`as part of flow(need to run after init )

*Note* that those needed to be run a in main folder and in each module folder (e.g. monitoring and ratingservice).

**Comment by minherz** [comment]
Fixed in 0.8.1
