### ISSUE TITLE
Add tests to make sure services are healthy

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#838]
We want to make sure fresh sandboxes don't have any errors. Either error logs, or failing SLOs

**Comment by daniel-sanche** [comment]
Also, the previous comment was focused on the GKE code, but we also have a new service running on App Engine. So after the GKE part, you'll have to do the same [deploy,](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/main/CONTRIBUTING.md#-run-app-engine-rating-micro-service) view logs, and write tests steps against that one too. But we can do that part at the end

**Comment by daniel-sanche** [comment]
This is partially addressed in https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/932, although we may want to check for error logs. (It currently just checks to make sure logs are coming in)

**Comment by minherz** [comment]
Correctness of Online Boutique is controlled via the pinned version in kustomization configuration.
