### ISSUE TITLE
Fix previous release tags

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#872]
There was recently a [terraform dependency update that broke old releases](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/864). That means all the old version tags of this repo are now broken. We should find a way to address this

Options:
- remove old tags
- mark old tags as deprecated
- create new branches for each old version, and fix the bug on each branch

**Comment by arbrown** [comment]
@daniel-sanche PTAL - Let us know if the next release will need this, or if we can safely put this back on P3.

**Comment by daniel-sanche** [comment]
It is a real issue that some of the old release tags would now be broken due to dependency shift if you tried to deploy using the old tags. That said, it's advertised as an alpha product, so I don't really think that needs to be fixed. Maybe just mark them as deprecated on the releases page or something?

**Comment by minherz** [comment]
We will close this issue and mark all releases prior to 0.8.0 as deprecated then.
