### ISSUE TITLE
Add alert on dependency updates

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#873]
We [recently had an issue where a terraform dependency updated and broke our released code](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/864). One of the brainstormed solutions to this problem would be to create an alert to warn us on dependency updates

This may be less of a problem with pinned versions, but we should still spend some time considering how this could be implemented

**Comment by minherz** [comment]
All TF provider versions are pinned.
