### ISSUE TITLE
Ensure dependency bot is tracking terraform dependencies

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#874]
[We recently had an issue where a terraform dependency updated and broke our released code](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/864). I believe this repo should have a bot to catch these issues and auto-update dependencies (dependabot, rennovatebot, or both), but we should confirm this

**Comment by minherz** [comment]
Dependency bot is currently not used in the project
