### ISSUE TITLE
Ratings Service - python requirements.txt pyparsing version

### ISSUE THREAD

**Issue by balldarrens** [GoogleCloudPlatform/cloud-ops-sandbox#877]
File:
https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/main/src/ratingservice/requirements.txt
Issue: pyparsing needs to be explicity added as a requirement to avoid the error below.

Issue in main, develop branches.

uwsgi==2.0.19.1
flask==1.1.4
psycopg2-binary==2.8.5
pyparsing==2.4.7
google-python-cloud-debugger

Full deployment with no issues.

╷
│ Error: Error waiting to create StandardAppVersion: Error waiting for Creating StandardAppVersion: Error code 9, message: Cloud build de469eea-4904-4c02-9f11-f135cb7594b0 status: FAILURE
│ found incompatible dependencies: "packaging 21.2 has requirement pyparsing<3,>=2.0.2, but you have pyparsing 3.0.6."
│ Full build logs: https://console.cloud.google.com/cloud-build/builds;region=us-east1/de469eea-4904-4c02-9f11-f135cb7594b0?project=792025362782
│
│   with module.ratingservice.google_app_engine_standard_app_version.default[0],
│   on ratingservice/main.tf line 117, in resource "google_app_engine_standard_app_version" "default":
│  117: resource "google_app_engine_standard_app_version" "default" {
│
╵

**Comment by daniel-sanche** [comment]
This will be fixed in a new v0.7.3 release
