### ISSUE TITLE
Add test that deploys through the Cloud Shell UI

### ISSUE THREAD

**Issue by daniel-sanche** [GoogleCloudPlatform/cloud-ops-sandbox#911]
We have E2E tests that build and test our custom cloud shell image in Docker. Real users use the Cloud Shell UI to deploy our image, which often has errors that don't arise when deploying though Docker.

We should consider adding tests that track a full E2E deployment using the Cloud Shell UI directly, in a headless browser session.

**Comment by daniel-sanche** [comment]
It's not a headless browser session, but I added `sandboxctl test` in [this PR](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/932), which should help in running tests against true Cloud Shell environments

**Comment by minherz** [comment]
This issue wan't be fixed because the next versions of Sandbox will no longer be using a custom Cloud Shell image.
