### ISSUE TITLE
RFE add a flag to sandboxctl to skip deploying the ratingservice

### ISSUE THREAD

**Issue by vishal84** [GoogleCloudPlatform/cloud-ops-sandbox#916]
[Request for Enhancement]

Our team currently consumes this repository for self paced lab exercises students leverage with an ephemeral GCP project to go through the various scenarios that the cloud ops sandbox provides. We would like to request an additional flag be added to the sandboxctl tool to skip the deployment of the ratingservice as that would reduce the amount of time it takes to provision the workloads required to go through the exercises in the README.md.

**Comment by daniel-sanche** [comment]
This has now been addressed in https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/923 and will be in the next release
