### ISSUE TITLE
Terraform manifest(s) assume default network is in place

### ISSUE THREAD

**Issue by mattycourtney** [GoogleCloudPlatform/cloud-ops-sandbox#989]
The Terraform manifest(s) assume default network is in place. This is problematic when the Org Poilicy `constraints/compute.skipDefaultNetworkCreation` is enforced. 

```
Error: googleapi: Error 400: Project "cloud-ops-sandbox-1961117772" has no network named "default"., badRequest
│
│   with google_container_cluster.gke,
│   on 03_gke_cluster.tf line 43, in resource "google_container_cluster" "gke":
│   43: resource "google_container_cluster" "gke" {
```

**Comment by minherz** [comment]
@mattycourtney thank you for reporting the problem. We are currently in the process of re-architecting the project. The part of the work is to detach the microservice demo from the Sandbox itself. In result, the Sandbox will be working with [Online Boutique][1] project. I will notify the maintainer of the Online Boutique about the request.

[1]: https://github.com/GoogleCloudPlatform/microservices-demo

**Comment by minherz** [comment]
Online Boutique has a new issue ([#1265][1]) to track the requested functionality.

[1]: https://github.com/GoogleCloudPlatform/microservices-demo/issues/1265
