### ISSUE TITLE
Migrate to Artifact Registry from Container Registry

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/cloud-ops-sandbox#992]
* Today, Cloud Ops Sandbox uses Google Cloud's [Container Registry](https://cloud.google.com/container-registry/docs) for the container images that it published.
* For instance, `gcr.io/stackdriver-sandbox-230822/sandbox/productcatalogservice:v0.8.1` is hosted on Container Registry.
* However, Artifact Registry is the recommended way to host container images on Google Cloud — not Container Registry.
* Relevant documentation: [Transition from Container Registry](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr).
* We should migrate to Artifact Registry.

### Additional Info
* I've created a similar GitHub issue on Online Boutique: https://github.com/GoogleCloudPlatform/microservices-demo/issues/1339, with a priority of `p2`.

**Comment by minherz** [comment]
Closing this issue due to removal of use in containers in the next (0.9) release.
